Numpy (Numeric Python)

In [5]:
!pip install numpy

In [6]:
import numpy as np

n1 = np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [7]:
p1 = [1,2,3,4,5]
p1

[1, 2, 3, 4, 5]

In [8]:
type(n1)

numpy.ndarray

In [9]:
type(p1)

list

In [10]:
py_list = list(range(1_000_000))
np_array = np.array(py_list)

In [11]:
%%timeit
[x+1 for x in py_list]

79.8 ms ± 4.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%%timeit
np_array+ 1

1.51 ms ± 68.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
### scalar, vector, matrix, tensor
### 1d, 2d, 3d ndarrayler
### transpoz, diskr

In [15]:
scalar_arr = np.array(1)
scalar_arr

array(1)

In [17]:
vector_arr = np.array([10, 20, 30])
vector_arr

array([10, 20, 30])

In [19]:
#arrayin boyutunu öğrenmek
# ndim -> n dimension
vector_arr.ndim

1

In [31]:
vector_arr2 = np.array([50, 60, 70])
vector_arr2

array([50, 60, 70])

In [33]:
#arrayler arası işlemler (vector)
result = vector_arr + vector_arr2
result

array([ 60,  80, 100])

(Shape) şekil arrayler arası işlem için uyuşma sağlamalıdır.

In [38]:
arr1 = np.array([10, 20])
arr2 = np.array([30, 40, 50])

arr1.shape, arr2.shape, arr1 + arr2

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [44]:
arr3 = np.array(
    [
        [10, 20, 30],
        [30, 40, 50]
    ]
)
arr3.ndim, arr3.shape

(2, (2, 3))

In [46]:
arr4 = np.array(
    [
        [60, 70, 80],
        [90, 100, 110]
    ]
)
arr4.ndim, arr4.shape

(2, (2, 3))

In [52]:
result = arr3 + arr4
result

array([[ 70,  90, 110],
       [120, 140, 160]])

In [56]:
result = arr4 - arr3
result

array([[50, 50, 50],
       [60, 60, 60]])

In [58]:
arr5 = np.array(
    [
        [30, 40],
        [50, 60],
        [70, 80]
    ]
)
arr5.ndim, arr5.shape

(2, (3, 2))

In [64]:
# (2,3) shape ile (3,2) sahpe matris toplamı?
#sahpelerin uygun olması lazım
arr4 + arr5

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [66]:
#reshape işlemi
arr5.reshape(2,3)

array([[30, 40, 50],
       [60, 70, 80]])

In [68]:
arr4 * arr5.reshape(2,3)

array([[1800, 2800, 4000],
       [5400, 7000, 8800]])

In [78]:
# dot product -> iç çarpım, nokta çarpım
#arr4.shape, arr5.shape
# ilk  matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olmalı.
result = np.dot(arr4, arr5)
result

array([[10900, 13000],
       [15400, 18400]])

In [81]:
arr4, arr5

(array([[ 60,  70,  80],
        [ 90, 100, 110]]),
 array([[30, 40],
        [50, 60],
        [70, 80]]))

In [83]:
# dot product nerede ihtiyaç duyulur? -> benxerlik, projeksiyon, lineer kombinasyon

Tensor

In [100]:
tensor1 = np.array(
    [
        [ [10,20], [30,40], [50,60] ],
        [ [70,80], [90,100], [110,120] ],
        [ [70,80], [90,100], [110,120] ],
        [ [70,80], [90,100], [110,120] ]
    ]
)
tensor1.ndim, tensor1.shape

(3, (4, 3, 2))

In [102]:
tensor1.size

24

In [108]:
tensor2 = np.random.randint(0, 256, (100,100,3))
tensor2

array([[[166,  16, 242],
        [105, 221, 180],
        [ 58,  59, 150],
        ...,
        [243,  26, 169],
        [ 88,   6,  25],
        [129, 229,  75]],

       [[ 25,  14, 100],
        [192,  45,  89],
        [ 28,  41, 162],
        ...,
        [251, 127, 138],
        [225, 205, 144],
        [ 81, 180, 159]],

       [[244,  33, 219],
        [102,  67, 198],
        [154, 115, 229],
        ...,
        [  9, 138,  13],
        [110, 205,  94],
        [159, 239,  37]],

       ...,

       [[219,  72, 145],
        [202,  20,  98],
        [138, 191, 149],
        ...,
        [ 30, 105,  55],
        [122, 165, 196],
        [ 34, 242,  65]],

       [[ 20, 193, 217],
        [213, 222, 218],
        [ 12,  65,  85],
        ...,
        [174, 184, 157],
        [158,  79,  88],
        [ 22, 186,  28]],

       [[ 45, 168, 203],
        [159, 211,  43],
        [188, 106,  70],
        ...,
        [ 52,   1, 236],
        [171, 216,  26],
        [ 22, 108, 119]]

In [110]:
from PIL import Image

In [112]:
image = Image.open("kedi.jpg")

In [116]:
image_array = np.array(image)

In [120]:
image_array.shape

(1500, 1000, 3)

In [122]:
image_array

array([[[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       [[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       [[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       ...,

       [[  2,   2,   4],
        [  2,   2,   4],
        [  2,   2,   4],
        ...,
        [ 35,  25,  23],
        [ 35,  25,  23],
        [ 35,  25,  23]],

       [[  2,   2,   4],
        [  2,   2,   4],
        [  2,   2,   4],
        ...,
        [ 36,  26,  24],
        [ 36,  26,  24],
        [ 36,  26,  24]],

       [[  3,   3,   5],
        [  3,   3,   5],
        [  3,   3,   5],
        ...,
        [ 37,  27,  25],
        [ 37,  27,  25],
        [ 37,  27,  25]]